### ISSUE TITLE
Combination of specified units + narrow distances seem fail

### ISSUE THREAD

**Issue by swernerx** [yahoo/intl-relativeformat#58]
We are using intl-relativeformat inside react-intl to show a human readable date indicator like "Today", "Tomorrow" in front of the actual date.

Our code looks like this:

```
<FormattedRelative value={date} units='day' />
```

We recently discovered a bug which is quite ugly. We see things like "Yesterday" combined with todays date which is clearly a failure.

It seems to work fine when the `date` is in the middle of the day e.g. noon, but does not work for example in the night hours where relative formatting moves it into the previous day.

I checked out the repository and tried reproducing it. Indeed this was not very hard.

I added an additional helper to return todays day in the early morning:

```js
function early() {
    return new Date().setHours(1);
}
```

I then used that exact method inside the test suite:

```js
            it('should always output in the specified units', function () {
                var rf = new IntlRelativeFormat('en', {units: 'day'});

                expect(rf.format(now())).to.equal('today');
->            expect(rf.format(early())).to.equal('today');
                expect(rf.format(past(24 * 60 * 60 * 1000))).to.equal('yesterday');
                expect(rf.format(past(30 * 24 * 60 * 60 * 1000))).to.equal('30 days ago');
                expect(rf.format(future(24 * 60 * 60 * 1000))).to.equal('tomorrow');
                expect(rf.format(future(30 * 24 * 60 * 60 * 1000))).to.equal('in 30 days');
            });
```

It fails with this error:

```
1) IntlRelativeFormat #resolvedOptions() units should always output in the specified units:
     Error: expected 'yesterday' to equal 'today'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Context.<anonymous> (tests/index.js:158:47)
```

**Comment by swernerx** [comment]
Just for information. We found a work-around where we set the hours on the date object to `12` before passing it to the relative date formatting.

```js
    const parsed = new Date(value);

    // We work-around some treshold handling of relative date formatting
    // which is actually inherited from MomentJS. Unfortunately it jumps
    // days too quickly when only trying to output relative days. A feature
    // which makes perfectly sense when running in "best-fit" mode does
    // indeed not work well when selecting a single property.
    // After we tried to tweak the tresholds, which unfortunately does not
    // seem to work, I figured that the best approach going forward is to
    // just modify the hours of the incoming date to the middle of the day
    // which works around the tresholds pretty fine as it seems.
    // I opened a bug report for intl-relativeformat to track the issue:
    // https://github.com/yahoo/intl-relativeformat/issues/58
    const relative = parsed.setHours(12);

    return (
        <span>
            <FormattedRelative value={relative} units='day' />
            <span>, </span>
            <FormattedDate
                weekday='short'
                day='2-digit'
                month='2-digit'
                year='numeric'
                hour='numeric'
                minute='numeric'
                value={parsed}
            />
        </span>
    );
```

**Comment by PolGuixe** [comment]
We are also experiencing the same issue! Why the PR hasn't been merged?
